version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    env_file:
    - .env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
    - "5050:80"
    volumes:
    - ./data/pgadmin:/root/.pgadmin
    - ./data/pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
    - .env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge