version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8081:8081"
    depends_on:
        - redis
        
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   ports:
  #   - "5432:5432"
  #   volumes:
  #   - ./data/postgres:/var/lib/postgresql/data
  #   env_file:
  #   - .env
  #   networks:
  #   - postgres
 
  # pgadmin:
  #   links:
  #   - postgres:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   ports:
  #   - "5050:80"
  #   volumes:
  #   - ./data/pgadmin:/root/.pgadmin
  #   - ./data/pgadmin/servers.json:/pgadmin4/servers.json
  #   env_file:
  #   - .env
  #   networks:
  #   - postgres
 


# networks:
#   postgres:
#     driver: bridge